version: "3"
services:
  adminer:
    image: "adminer:latest"
    ports:
      - "8080:8080"
  saslauthd:
    environment:
      - MYSQL_MAIL_USER=vmail
      - MYSQL_MAIL_PASSWORD=vmaildbpass
      - MYSQL_MAIL_DB_NAME=vmail
      - MYSQL_HOST=mysql
    image: "saslauthd-deb:latest"
    volumes:
      # Mount socket that is shared with postfix and cyrus containers
      - saslsocket:/var/run/saslauthd
  cyrus:
    depends_on:
      - saslauthd
    environment:
      - CYRUS_ADMIN_ACCOUNTS=chris@waswiegentiere.de
    image: "cyrus3debnew:latest"
    ports:
      - "143:143"
    volumes:
      # Partition to use for mail data (slow)
      # - cyrus-maildata:/var/spool/cyrus/mail
      # Put your sieve scripts here:
      # - sieve-scripts:/var/spool/sieve
      # Partition to use for search index data (fast)
      # - cyrus-searchdata:/var/cyrus/search
      # Mount socket that is shared with postfix and saslauthd containers
      - saslsocket:/var/run/saslauthd
  postfix:
    depends_on:
      - saslauthd
    environment:
      - MYSQL_MAIL_USER=vmail
      - MYSQL_MAIL_PASSWORD=vmaildbpass
      - MYSQL_MAIL_DB_NAME=vmail
      - MYSQL_HOST=mysql
      - POSTFIX_MY_HOSTNAME=mail.waswiegentiere.de
      - POSTFIX_MY_ORIGIN=waswiegentiere.de
      - CYRUS_HOST=cyrus:2003
    image: "postfix3:latest"
    ports:
      - "25:25"
    volumes:
      - postfix-queue:/var/spool/postfix
      - postfix-data:/var/lib/postfix
      - postfix-mail-spool:/var/spool/mail
      # Mount socket that is shared with cyrus and saslauthd containers
      - saslsocket:/var/run/saslauthd
  mysql:
    image: "mariadb/server"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123CHANGEME
      MARIADB_ROOT_PASSWOR: 123CHANGEME
      # - MARIADB_ROOT_PASSWORD=123CHANGEME
    ports:
      - "3306:3306"

volumes:
  # TODO: actually mount these somewhere
  postfix-queue:
  postfix-data:
  postfix-mail-spool:
  cyrus-maildata:
  sieve-scripts:
  cyrus-searchdata:
  mysql-data:
  # This can just be an ephemeral storage as it is just for socket sharing
  saslsocket:
