version: "3"
services:
  saslauthd:
    environment:
      - DATABASE_MAIL_USER=vmail
      - DATABASE_MAIL_PASSWORD=vmaildbpass
      - DATABASE_MAIL_DB_NAME=vmail
      - DATABASE_HOST=mysql
    image: "chmanie/hemhem-saslauthd:latest"
    volumes:
      # Mount socket that is shared with postfix and cyrus containers
      - saslsocket:/var/run/saslauthd
  cyrus:
    depends_on:
      - saslauthd
    environment:
      - CYRUS_ADMIN_ACCOUNTS=chris@waswiegentiere.de
    image: "chmanie/hemhem-cyrus:latest"
    ports:
      - "143:143"
    volumes:
      # Partition to use for mail data (slow)
      - cyrus-maildata:/var/spool/cyrus/mail
      # Put your sieve scripts here:
      - sieve-scripts:/var/spool/sieve
      # Partition to use for search index data (fast)
      - cyrus-searchdata:/var/cyrus/search
      # Mount socket that is shared with postfix and saslauthd containers
      - saslsocket:/var/run/saslauthd
  postfix:
    depends_on:
      - saslauthd
    environment:
      - DATABASE_MAIL_USER=vmail
      - DATABASE_MAIL_PASSWORD=vmaildbpass
      - DATABASE_MAIL_DB_NAME=vmail
      - DATABASE_HOST=mysql
      - POSTFIX_MY_HOSTNAME=mail.waswiegentiere.de
      - POSTFIX_MY_ORIGIN=waswiegentiere.de
      - CYRUS_HOST=cyrus:2003
    image: "chmanie/hemhem-postfix:latest"
    ports:
      - "25:25"
    volumes:
      - postfix-queue:/var/spool/postfix
      - postfix-data:/var/lib/postfix
      - postfix-mail-spool:/var/spool/mail
      # Mount socket that is shared with cyrus and saslauthd containers
      - saslsocket:/var/run/saslauthd
  mysql:
    image: "mariadb/server"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=123CHANGEME
    ports:
      - "3306:3306"

volumes:
  # TODO: actually mount these somewhere
  postfix-queue:
  postfix-data:
  postfix-mail-spool:
  cyrus-maildata:
  sieve-scripts:
  cyrus-searchdata:
  mysql-data:
  # This can just be an ephemeral storage as it is just for socket sharing
  saslsocket:
