#!/bin/bash
set -e

DATABASE_MAIL_USER=${DATABASE_MAIL_USER:-vmail}
DATABASE_MAIL_PASSWORD=${DATABASE_MAIL_PASSWORD:-vmail}
DATABASE_HOST=${DATABASE_HOST:-mysql}
DATABASE_MAIL_DB_NAME=${DATABASE_MAIL_DB_NAME:-vmail}

sed -i s/{DATABASE_MAIL_USER}/${DATABASE_MAIL_USER}/ /etc/pam-mysql.conf
sed -i s/{DATABASE_MAIL_PASSWORD}/${DATABASE_MAIL_PASSWORD}/ /etc/pam-mysql.conf
sed -i s/{DATABASE_HOST}/${DATABASE_HOST}/ /etc/pam-mysql.conf
sed -i s/{DATABASE_MAIL_DB_NAME}/${DATABASE_MAIL_DB_NAME}/ /etc/pam-mysql.conf

exec rsyslogd -n &

saslauthd -a pam -c -r -m /var/run/saslauthd -d
