#!/bin/bash
set -e

MYSQL_MAIL_USER=${MYSQL_MAIL_USER:-vmail}
MYSQL_MAIL_PASSWORD=${MYSQL_MAIL_PASSWORD:-vmail}
MYSQL_HOST=${MYSQL_HOST:-mysql}
MYSQL_MAIL_DB_NAME=${MYSQL_MAIL_DB_NAME:-vmail}
POSTFIX_MY_HOSTNAME=${POSTFIX_MY_HOSTNAME:-mail.localhost}
POSTFIX_MY_ORIGIN=${POSTFIX_MY_ORIGIN:-localhost}
CYRUS_HOST=${CYRUS_HOST:-cyrus:2003}

sed -i s/{MYSQL_MAIL_USER}/${MYSQL_MAIL_USER}/ /etc/postfix/sql/*.cf
sed -i s/{MYSQL_MAIL_PASSWORD}/${MYSQL_MAIL_PASSWORD}/ /etc/postfix/sql/*.cf
sed -i s/{MYSQL_HOST}/${MYSQL_HOST}/ /etc/postfix/sql/*.cf
sed -i s/{MYSQL_MAIL_DB_NAME}/${MYSQL_MAIL_DB_NAME}/ /etc/postfix/sql/*.cf

sed -i s/{POSTFIX_MY_HOSTNAME}/${POSTFIX_MY_HOSTNAME}/ /etc/postfix/main.cf
sed -i s/{POSTFIX_MY_ORIGIN}/${POSTFIX_MY_ORIGIN}/ /etc/postfix/main.cf
sed -i s/{CYRUS_HOST}/${CYRUS_HOST}/ /etc/postfix/main.cf


if [[ -f /etc/aliases ]]; then
  sed -i '/^root:/d' /etc/aliases
fi
echo "root: postmaster" >> /etc/aliases
newaliases

if [[ -f "/usr/libexec/postfix/master" ]]; then
  cmd="/usr/libexec/postfix/master"
fi

if [[ -f "/usr/lib/postfix/master" ]]; then
  cmd="/usr/lib/postfix/master"
fi

if [[ -z "$cmd" ]]; then
  echo "Could not find postfix master in /usr/lib or /usr/libexec"
  exit 1
fi

"$cmd" -c /etc/postfix -d 2>&1
